version: '3.8'

services:
  chatbot-api:
    build: 
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./src:/app/src
      - ./data:/app/data
      - ./models:/app/models
    depends_on:
      - redis
      - postgres

  chainlit-ui:
    build:
      context: .
      dockerfile: docker/Dockerfile.chainlit
    ports:
      - "8000:8000"
    environment:
      - CHAINLIT_HOST=0.0.0.0
      - CHAINLIT_PORT=8000
      - API_URL=http://chatbot-api:5000
    volumes:
      - ./src:/app/src
    depends_on:
      - chatbot-api

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=chatbot_db
      - POSTGRES_USER=chatbot_user
      - POSTGRES_PASSWORD=chatbot_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  redis_data:
  postgres_data:
